import Head from 'next/head'

import Navbar from '../components/Navbar'
import Fellowship from '../components/Fellowship'
import ImpactStats from '../components/ImpactStats'
import NewsFeatures from '../components/NewsFeatures'
import Callout from '../components/Callout'
import Layout from '../components/Layout'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Home EN | Rotary International</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/rotary_icon.png" />
      </Head>

      <main className=' w-screen h-screen bg-white text-red-500'>
         <Navbar />
         <Fellowship />
         <ImpactStats />
         <NewsFeatures />
         <Callout />
         <Layout />
      </main>

      <footer>
        
      </footer>
    </div>
  )
}
